# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: cluster.proto for package 'gitaly'

require 'grpc'
require 'cluster_pb'

module Gitaly
  module RaftService
    # RaftService manages the sending of Raft messages to peers.
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'gitaly.RaftService'

      # SendMessage processes Raft messages and ensures they are handled by
      # the receiving node to update its Raft state machine.
      rpc :SendMessage, stream(::Gitaly::RaftMessageRequest), ::Gitaly::RaftMessageResponse
      # SendSnapshot sends raft snapshots from the leader to the follower node. Typically it
      # would be useful for nodes to catch up to the latest state.
      rpc :SendSnapshot, stream(::Gitaly::RaftSnapshotMessageRequest), ::Gitaly::RaftSnapshotMessageResponse
    end

    Stub = Service.rpc_stub_class
  end
end
