# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cluster.proto

require 'google/protobuf'

require 'lint_pb'
require 'raftpb/raft_pb'


descriptor_data = "\n\rcluster.proto\x12\x06gitaly\x1a\nlint.proto\x1a\x11raftpb/raft.proto\"o\n\tRaftEntry\x12\n\n\x02id\x18\x01 \x01(\x04\x12\'\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x19.gitaly.RaftEntry.LogData\x1a-\n\x07LogData\x12\x12\n\nlocal_path\x18\x01 \x01(\x0c\x12\x0e\n\x06packed\x18\x02 \x01(\x0c\"!\n\x10RaftPartitionKey\x12\r\n\x05value\x18\x01 \x01(\t\"\xbc\x02\n\tReplicaID\x12/\n\rpartition_key\x18\x01 \x01(\x0b\x32\x18.gitaly.RaftPartitionKey\x12\x11\n\tmember_id\x18\x02 \x01(\x04\x12\x14\n\x0cstorage_name\x18\x03 \x01(\t\x12,\n\x08metadata\x18\x04 \x01(\x0b\x32\x1a.gitaly.ReplicaID.Metadata\x12+\n\x04type\x18\x05 \x01(\x0e\x32\x1d.gitaly.ReplicaID.ReplicaType\x1a\x1b\n\x08Metadata\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"]\n\x0bReplicaType\x12\x1c\n\x18REPLICA_TYPE_UNSPECIFIED\x10\x00\x12\x16\n\x12REPLICA_TYPE_VOTER\x10\x01\x12\x18\n\x14REPLICA_TYPE_LEARNER\x10\x02\"q\n\x12RaftMessageRequest\x12\x12\n\ncluster_id\x18\x01 \x01(\t\x12%\n\nreplica_id\x18\x02 \x01(\x0b\x32\x11.gitaly.ReplicaID\x12 \n\x07message\x18\x03 \x01(\x0b\x32\x0f.raftpb.Message\"\x15\n\x13RaftMessageResponse\"v\n\x1aRaftSnapshotMessageRequest\x12.\n\x08raft_msg\x18\x01 \x01(\x0b\x32\x1a.gitaly.RaftMessageRequestH\x00\x12\x0f\n\x05\x63hunk\x18\x02 \x01(\x0cH\x00\x42\x17\n\x15raft_snapshot_payload\"I\n\x1bRaftSnapshotMessageResponse\x12\x13\n\x0b\x64\x65stination\x18\x01 \x01(\t\x12\x15\n\rsnapshot_size\x18\x02 \x01(\x04\x32\xc6\x01\n\x0bRaftService\x12R\n\x0bSendMessage\x12\x1a.gitaly.RaftMessageRequest\x1a\x1b.gitaly.RaftMessageResponse\"\x08\xfa\x97(\x04\x08\x01\x10\x02(\x01\x12\x63\n\x0cSendSnapshot\x12\".gitaly.RaftSnapshotMessageRequest\x1a#.gitaly.RaftSnapshotMessageResponse\"\x08\xfa\x97(\x04\x08\x01\x10\x02(\x01\x42\x34Z2gitlab.com/gitlab-org/gitaly/v16/proto/go/gitalypbb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError => e
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
    ["raftpb.Message", "raftpb/raft.proto"],
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

module Gitaly
  RaftEntry = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.RaftEntry").msgclass
  RaftEntry::LogData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.RaftEntry.LogData").msgclass
  RaftPartitionKey = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.RaftPartitionKey").msgclass
  ReplicaID = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.ReplicaID").msgclass
  ReplicaID::Metadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.ReplicaID.Metadata").msgclass
  ReplicaID::ReplicaType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.ReplicaID.ReplicaType").enummodule
  RaftMessageRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.RaftMessageRequest").msgclass
  RaftMessageResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.RaftMessageResponse").msgclass
  RaftSnapshotMessageRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.RaftSnapshotMessageRequest").msgclass
  RaftSnapshotMessageResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.RaftSnapshotMessageResponse").msgclass
end
