AllCops:
  TargetRubyVersion: 2.7

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Naming/VariableNumber:
  EnforcedStyle: snake_case
