# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: internal/module/managed_resources/rpc/rpc.proto for package 'gitlab.agent.managed_resources.rpc'

require 'grpc'
require 'internal/module/managed_resources/rpc/rpc_pb'

module Gitlab
  module Agent
    module ManagedResources
      module Rpc
        module Provisioner
          class Service

            include ::GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = 'gitlab.agent.managed_resources.rpc.Provisioner'

            rpc :GetDefaultEnvironmentTemplate, ::Gitlab::Agent::ManagedResources::Rpc::GetDefaultEnvironmentTemplateRequest, ::Gitlab::Agent::ManagedResources::Rpc::GetDefaultEnvironmentTemplateResponse
            rpc :ListEnvironmentTemplates, ::Gitlab::Agent::ManagedResources::Rpc::ListEnvironmentTemplatesRequest, ::Gitlab::Agent::ManagedResources::Rpc::ListEnvironmentTemplatesResponse
            rpc :GetEnvironmentTemplate, ::Gitlab::Agent::ManagedResources::Rpc::GetEnvironmentTemplateRequest, ::Gitlab::Agent::ManagedResources::Rpc::GetEnvironmentTemplateResponse
            rpc :RenderEnvironmentTemplate, ::Gitlab::Agent::ManagedResources::Rpc::RenderEnvironmentTemplateRequest, ::Gitlab::Agent::ManagedResources::Rpc::RenderEnvironmentTemplateResponse
            rpc :EnsureEnvironment, ::Gitlab::Agent::ManagedResources::Rpc::EnsureEnvironmentRequest, ::Gitlab::Agent::ManagedResources::Rpc::EnsureEnvironmentResponse
            rpc :DeleteEnvironment, ::Gitlab::Agent::ManagedResources::Rpc::DeleteEnvironmentRequest, ::Gitlab::Agent::ManagedResources::Rpc::DeleteEnvironmentResponse
          end

          Stub = Service.rpc_stub_class
        end
      end
    end
  end
end
